import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        for (int i = 0; i < 5; i++) {
            int x = sc.nextInt();
            if (x == 1) {
                System.out.println("          |");
                System.out.println("       \\  |  /");
                System.out.println("        \\ | /");
                System.out.println("         \\|/");
                System.out.println("       XXXXXXX");
                System.out.println("      X       X");
                System.out.println("     X  O   O  X");
                System.out.println("    X     V     X");
                System.out.println("W   X  X     X  X");
                System.out.println(" \\   X  XXXXX  X");
                System.out.println("  \\   X       X");
                System.out.println("   \\   XXXXXXX");
                System.out.println("    \\ X       X---");
                System.out.println("     X    O    X  \\");
                System.out.println("    X           X  \\");
                System.out.println("     XXXXXXXXXXX    \\");
                System.out.println("      OOOO OOOO      M");
                System.out.print("      OOOO OOOO");
            } else if (x == 2) {
                System.out.println("           |");
                System.out.println("        \\  |  /");
                System.out.println("         \\ | /");
                System.out.println("          \\|/");
                System.out.println("        XXXXXXX");
                System.out.println("       X       X");
                System.out.println("      X  O   O  X");
                System.out.println("     X     V     X");
                System.out.println(" W   X  X     X  X");
                System.out.println("  \\   X  XXXXX  X");
                System.out.println("   \\   X       X");
                System.out.println("    \\   XXXXXXX");
                System.out.println("     \\ X       X---");
                System.out.println("      X    O    X  \\");
                System.out.println("     X           X  \\");
                System.out.println("      XXXXXXXXXXX    \\");
                System.out.println("      X         X     M");
                System.out.println("     X     O     X");
                System.out.println("    X      O      X");
                System.out.println("   X               X");
                System.out.println("    XXXXXXXXXXXXXXX");
                System.out.println("       OOOO OOOO");
                System.out.print("       OOOO OOOO");
            } else if (x == 3) {
                System.out.println("           |");
                System.out.println("        \\  |  /");
                System.out.println("         \\ | /");
                System.out.println("          \\|/");
                System.out.println("        XXXXXXX");
                System.out.println("       X       X");
                System.out.println("      X  O   O  X");
                System.out.println("     X     V     X");
                System.out.println(" W   X  X     X  X");
                System.out.println("  \\   X  XXXXX  X");
                System.out.println("   \\   X       X");
                System.out.println("    \\   XXXXXXX");
                System.out.println("     \\ X       X---");
                System.out.println("      X    O    X  \\");
                System.out.println("     X           X  \\");
                System.out.println("      XXXXXXXXXXX    \\");
                System.out.println("      X         X     M");
                System.out.println("     X     O     X");
                System.out.println("    X      O      X");
                System.out.println("   X               X");
                System.out.println("    XXXXXXXXXXXXXXX");
                System.out.println("    X             X");
                System.out.println("   X       O       X");
                System.out.println("  X        O        X");
                System.out.println(" X         O         X");
                System.out.println("X                     X");
                System.out.println(" XXXXXXXXXXXXXXXXXXXXX");
                System.out.println("       OOOO OOOO");
                System.out.print("       OOOO OOOO");
            } else if (x == 4) {
                System.out.println("               |");
                System.out.println("            \\  |  /");
                System.out.println("             \\ | /");
                System.out.println("              \\|/");
                System.out.println("            XXXXXXX");
                System.out.println("           X       X");
                System.out.println("          X  O   O  X");
                System.out.println("         X     V     X");
                System.out.println("     W   X  X     X  X");
                System.out.println("      \\   X  XXXXX  X");
                System.out.println("       \\   X       X");
                System.out.println("        \\   XXXXXXX");
                System.out.println("         \\ X       X---");
                System.out.println("          X    O    X  \\");
                System.out.println("         X           X  \\");
                System.out.println("          XXXXXXXXXXX    \\");
                System.out.println("          X         X     M");
                System.out.println("         X     O     X");
                System.out.println("        X      O      X");
                System.out.println("       X               X");
                System.out.println("        XXXXXXXXXXXXXXX");
                System.out.println("        X             X");
                System.out.println("       X       O       X");
                System.out.println("      X        O        X");
                System.out.println("     X         O         X");
                System.out.println("    X                     X");
                System.out.println("     XXXXXXXXXXXXXXXXXXXXX");
                System.out.println("     X                   X");
                System.out.println("    X          O          X");
                System.out.println("   X           O           X");
                System.out.println("  X            O            X");
                System.out.println(" X             O             X");
                System.out.println("X                             X");
                System.out.println(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("           OOOO OOOO");
                System.out.print("           OOOO OOOO");
            } else if (x == 5) {
                System.out.println("                    |");
                System.out.println("                 \\  |  /");
                System.out.println("                  \\ | /");
                System.out.println("                   \\|/");
                System.out.println("                 XXXXXXX");
                System.out.println("                X       X");
                System.out.println("               X  O   O  X");
                System.out.println("              X     V     X");
                System.out.println("          W   X  X     X  X");
                System.out.println("           \\   X  XXXXX  X");
                System.out.println("            \\   X       X");
                System.out.println("             \\   XXXXXXX");
                System.out.println("              \\ X       X---");
                System.out.println("               X    O    X  \\");
                System.out.println("              X           X  \\");
                System.out.println("               XXXXXXXXXXX    \\");
                System.out.println("               X         X     M");
                System.out.println("              X     O     X");
                System.out.println("             X      O      X");
                System.out.println("            X               X");
                System.out.println("             XXXXXXXXXXXXXXX");
                System.out.println("             X             X");
                System.out.println("            X       O       X");
                System.out.println("           X        O        X");
                System.out.println("          X         O         X");
                System.out.println("         X                     X");
                System.out.println("          XXXXXXXXXXXXXXXXXXXXX");
                System.out.println("          X                   X");
                System.out.println("         X          O          X");
                System.out.println("        X           O           X");
                System.out.println("       X            O            X");
                System.out.println("      X             O             X");
                System.out.println("     X                             X");
                System.out.println("      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("      X                           X");
                System.out.println("     X              O              X");
                System.out.println("    X               O               X");
                System.out.println("   X                O                X");
                System.out.println("  X                 O                 X");
                System.out.println(" X                  O                  X");
                System.out.println("X                                       X");
                System.out.println(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                OOOO OOOO");
                System.out.print("                OOOO OOOO");
            } else if (x == 6) {
                System.out.println("                          |");
                System.out.println("                       \\  |  /");
                System.out.println("                        \\ | /");
                System.out.println("                         \\|/");
                System.out.println("                       XXXXXXX");
                System.out.println("                      X       X");
                System.out.println("                     X  O   O  X");
                System.out.println("                    X     V     X");
                System.out.println("                W   X  X     X  X");
                System.out.println("                 \\   X  XXXXX  X");
                System.out.println("                  \\   X       X");
                System.out.println("                   \\   XXXXXXX");
                System.out.println("                    \\ X       X---");
                System.out.println("                     X    O    X  \\");
                System.out.println("                    X           X  \\");
                System.out.println("                     XXXXXXXXXXX    \\");
                System.out.println("                     X         X     M");
                System.out.println("                    X     O     X");
                System.out.println("                   X      O      X");
                System.out.println("                  X               X");
                System.out.println("                   XXXXXXXXXXXXXXX");
                System.out.println("                   X             X");
                System.out.println("                  X       O       X");
                System.out.println("                 X        O        X");
                System.out.println("                X         O         X");
                System.out.println("               X                     X");
                System.out.println("                XXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                X                   X");
                System.out.println("               X          O          X");
                System.out.println("              X           O           X");
                System.out.println("             X            O            X");
                System.out.println("            X             O             X");
                System.out.println("           X                             X");
                System.out.println("            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("            X                           X");
                System.out.println("           X              O              X");
                System.out.println("          X               O               X");
                System.out.println("         X                O                X");
                System.out.println("        X                 O                 X");
                System.out.println("       X                  O                  X");
                System.out.println("      X                                       X");
                System.out.println("       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("       X                                     X");
                System.out.println("      X                   O                   X");
                System.out.println("     X                    O                    X");
                System.out.println("    X                     O                     X");
                System.out.println("   X                      O                      X");
                System.out.println("  X                       O                       X");
                System.out.println(" X                        O                        X");
                System.out.println("X                                                   X");
                System.out.println(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                      OOOO OOOO");
                System.out.print("                      OOOO OOOO");
            } else if (x == 7) {
                System.out.println("                                 |");
                System.out.println("                              \\  |  /");
                System.out.println("                               \\ | /");
                System.out.println("                                \\|/");
                System.out.println("                              XXXXXXX");
                System.out.println("                             X       X");
                System.out.println("                            X  O   O  X");
                System.out.println("                           X     V     X");
                System.out.println("                       W   X  X     X  X");
                System.out.println("                        \\   X  XXXXX  X");
                System.out.println("                         \\   X       X");
                System.out.println("                          \\   XXXXXXX");
                System.out.println("                           \\ X       X---");
                System.out.println("                            X    O    X  \\");
                System.out.println("                           X           X  \\");
                System.out.println("                            XXXXXXXXXXX    \\");
                System.out.println("                            X         X     M");
                System.out.println("                           X     O     X");
                System.out.println("                          X      O      X");
                System.out.println("                         X               X");
                System.out.println("                          XXXXXXXXXXXXXXX");
                System.out.println("                          X             X");
                System.out.println("                         X       O       X");
                System.out.println("                        X        O        X");
                System.out.println("                       X         O         X");
                System.out.println("                      X                     X");
                System.out.println("                       XXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                       X                   X");
                System.out.println("                      X          O          X");
                System.out.println("                     X           O           X");
                System.out.println("                    X            O            X");
                System.out.println("                   X             O             X");
                System.out.println("                  X                             X");
                System.out.println("                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                   X                           X");
                System.out.println("                  X              O              X");
                System.out.println("                 X               O               X");
                System.out.println("                X                O                X");
                System.out.println("               X                 O                 X");
                System.out.println("              X                  O                  X");
                System.out.println("             X                                       X");
                System.out.println("              XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("              X                                     X");
                System.out.println("             X                   O                   X");
                System.out.println("            X                    O                    X");
                System.out.println("           X                     O                     X");
                System.out.println("          X                      O                      X");
                System.out.println("         X                       O                       X");
                System.out.println("        X                        O                        X");
                System.out.println("       X                                                   X");
                System.out.println("        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("        X                                                 X");
                System.out.println("       X                         O                         X");
                System.out.println("      X                          O                          X");
                System.out.println("     X                           O                           X");
                System.out.println("    X                            O                            X");
                System.out.println("   X                             O                             X");
                System.out.println("  X                              O                              X");
                System.out.println(" X                               O                               X");
                System.out.println("X                                                                 X");
                System.out.println(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                             OOOO OOOO");
                System.out.print("                             OOOO OOOO");
            } else if (x == 8) {
                System.out.println("                                         |");
                System.out.println("                                      \\  |  /");
                System.out.println("                                       \\ | /");
                System.out.println("                                        \\|/");
                System.out.println("                                      XXXXXXX");
                System.out.println("                                     X       X");
                System.out.println("                                    X  O   O  X");
                System.out.println("                                   X     V     X");
                System.out.println("                               W   X  X     X  X");
                System.out.println("                                \\   X  XXXXX  X");
                System.out.println("                                 \\   X       X");
                System.out.println("                                  \\   XXXXXXX");
                System.out.println("                                   \\ X       X---");
                System.out.println("                                    X    O    X  \\");
                System.out.println("                                   X           X  \\");
                System.out.println("                                    XXXXXXXXXXX    \\");
                System.out.println("                                    X         X     M");
                System.out.println("                                   X     O     X");
                System.out.println("                                  X      O      X");
                System.out.println("                                 X               X");
                System.out.println("                                  XXXXXXXXXXXXXXX");
                System.out.println("                                  X             X");
                System.out.println("                                 X       O       X");
                System.out.println("                                X        O        X");
                System.out.println("                               X         O         X");
                System.out.println("                              X                     X");
                System.out.println("                               XXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                               X                   X");
                System.out.println("                              X          O          X");
                System.out.println("                             X           O           X");
                System.out.println("                            X            O            X");
                System.out.println("                           X             O             X");
                System.out.println("                          X                             X");
                System.out.println("                           XXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                           X                           X");
                System.out.println("                          X              O              X");
                System.out.println("                         X               O               X");
                System.out.println("                        X                O                X");
                System.out.println("                       X                 O                 X");
                System.out.println("                      X                  O                  X");
                System.out.println("                     X                                       X");
                System.out.println("                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                      X                                     X");
                System.out.println("                     X                   O                   X");
                System.out.println("                    X                    O                    X");
                System.out.println("                   X                     O                     X");
                System.out.println("                  X                      O                      X");
                System.out.println("                 X                       O                       X");
                System.out.println("                X                        O                        X");
                System.out.println("               X                                                   X");
                System.out.println("                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                X                                                 X");
                System.out.println("               X                         O                         X");
                System.out.println("              X                          O                          X");
                System.out.println("             X                           O                           X");
                System.out.println("            X                            O                            X");
                System.out.println("           X                             O                             X");
                System.out.println("          X                              O                              X");
                System.out.println("         X                               O                               X");
                System.out.println("        X                                                                 X");
                System.out.println("         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("         X                                                               X");
                System.out.println("        X                                O                                X");
                System.out.println("       X                                 O                                 X");
                System.out.println("      X                                  O                                  X");
                System.out.println("     X                                   O                                   X");
                System.out.println("    X                                    O                                    X");
                System.out.println("   X                                     O                                     X");
                System.out.println("  X                                      O                                      X");
                System.out.println(" X                                       O                                       X");
                System.out.println("X                                                                                 X");
                System.out.println(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                                     OOOO OOOO");
                System.out.print("                                     OOOO OOOO");
            }
            else if(x == 9){
                System.out.println("                                                  |");
                System.out.println("                                               \\  |  /");
                System.out.println("                                                \\ | /");
                System.out.println("                                                 \\|/");
                System.out.println("                                               XXXXXXX");
                System.out.println("                                              X       X");
                System.out.println("                                             X  O   O  X");
                System.out.println("                                            X     V     X");
                System.out.println("                                        W   X  X     X  X");
                System.out.println("                                         \\   X  XXXXX  X");
                System.out.println("                                          \\   X       X");
                System.out.println("                                           \\   XXXXXXX");
                System.out.println("                                            \\ X       X---");
                System.out.println("                                             X    O    X  \\");
                System.out.println("                                            X           X  \\");
                System.out.println("                                             XXXXXXXXXXX    \\");
                System.out.println("                                             X         X     M");
                System.out.println("                                            X     O     X");
                System.out.println("                                           X      O      X");
                System.out.println("                                          X               X");
                System.out.println("                                           XXXXXXXXXXXXXXX");
                System.out.println("                                           X             X");
                System.out.println("                                          X       O       X");
                System.out.println("                                         X        O        X");
                System.out.println("                                        X         O         X");
                System.out.println("                                       X                     X");
                System.out.println("                                        XXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                                        X                   X");
                System.out.println("                                       X          O          X");
                System.out.println("                                      X           O           X");
                System.out.println("                                     X            O            X");
                System.out.println("                                    X             O             X");
                System.out.println("                                   X                             X");
                System.out.println("                                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                                    X                           X");
                System.out.println("                                   X              O              X");
                System.out.println("                                  X               O               X");
                System.out.println("                                 X                O                X");
                System.out.println("                                X                 O                 X");
                System.out.println("                               X                  O                  X");
                System.out.println("                              X                                       X");
                System.out.println("                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                               X                                     X");
                System.out.println("                              X                   O                   X");
                System.out.println("                             X                    O                    X");
                System.out.println("                            X                     O                     X");
                System.out.println("                           X                      O                      X");
                System.out.println("                          X                       O                       X");
                System.out.println("                         X                        O                        X");
                System.out.println("                        X                                                   X");
                System.out.println("                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                         X                                                 X");
                System.out.println("                        X                         O                         X");
                System.out.println("                       X                          O                          X");
                System.out.println("                      X                           O                           X");
                System.out.println("                     X                            O                            X");
                System.out.println("                    X                             O                             X");
                System.out.println("                   X                              O                              X");
                System.out.println("                  X                               O                               X");
                System.out.println("                 X                                                                 X");
                System.out.println("                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                  X                                                               X");
                System.out.println("                 X                                O                                X");
                System.out.println("                X                                 O                                 X");
                System.out.println("               X                                  O                                  X");
                System.out.println("              X                                   O                                   X");
                System.out.println("             X                                    O                                    X");
                System.out.println("            X                                     O                                     X");
                System.out.println("           X                                      O                                      X");
                System.out.println("          X                                       O                                       X");
                System.out.println("         X                                                                                 X");
                System.out.println("          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("          X                                                                               X");
                System.out.println("         X                                        O                                        X");
                System.out.println("        X                                         O                                         X");
                System.out.println("       X                                          O                                          X");
                System.out.println("      X                                           O                                           X");
                System.out.println("     X                                            O                                            X");
                System.out.println("    X                                             O                                             X");
                System.out.println("   X                                              O                                              X");
                System.out.println("  X                                               O                                               X");
                System.out.println(" X                                                O                                                X");
                System.out.println("X                                                                                                   X");
                System.out.println(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                                              OOOO OOOO");
                System.out.print("                                              OOOO OOOO");
            }
            else if(x == 10){
                System.out.println("                                                            |");
                System.out.println("                                                         \\  |  /");
                System.out.println("                                                          \\ | /");
                System.out.println("                                                           \\|/");
                System.out.println("                                                         XXXXXXX");
                System.out.println("                                                        X       X");
                System.out.println("                                                       X  O   O  X");
                System.out.println("                                                      X     V     X");
                System.out.println("                                                  W   X  X     X  X");
                System.out.println("                                                   \\   X  XXXXX  X");
                System.out.println("                                                    \\   X       X");
                System.out.println("                                                     \\   XXXXXXX");
                System.out.println("                                                      \\ X       X---");
                System.out.println("                                                       X    O    X  \\");
                System.out.println("                                                      X           X  \\");
                System.out.println("                                                       XXXXXXXXXXX    \\");
                System.out.println("                                                       X         X     M");
                System.out.println("                                                      X     O     X");
                System.out.println("                                                     X      O      X");
                System.out.println("                                                    X               X");
                System.out.println("                                                     XXXXXXXXXXXXXXX");
                System.out.println("                                                     X             X");
                System.out.println("                                                    X       O       X");
                System.out.println("                                                   X        O        X");
                System.out.println("                                                  X         O         X");
                System.out.println("                                                 X                     X");
                System.out.println("                                                  XXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                                                  X                   X");
                System.out.println("                                                 X          O          X");
                System.out.println("                                                X           O           X");
                System.out.println("                                               X            O            X");
                System.out.println("                                              X             O             X");
                System.out.println("                                             X                             X");
                System.out.println("                                              XXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                                              X                           X");
                System.out.println("                                             X              O              X");
                System.out.println("                                            X               O               X");
                System.out.println("                                           X                O                X");
                System.out.println("                                          X                 O                 X");
                System.out.println("                                         X                  O                  X");
                System.out.println("                                        X                                       X");
                System.out.println("                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                                         X                                     X");
                System.out.println("                                        X                   O                   X");
                System.out.println("                                       X                    O                    X");
                System.out.println("                                      X                     O                     X");
                System.out.println("                                     X                      O                      X");
                System.out.println("                                    X                       O                       X");
                System.out.println("                                   X                        O                        X");
                System.out.println("                                  X                                                   X");
                System.out.println("                                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                                   X                                                 X");
                System.out.println("                                  X                         O                         X");
                System.out.println("                                 X                          O                          X");
                System.out.println("                                X                           O                           X");
                System.out.println("                               X                            O                            X");
                System.out.println("                              X                             O                             X");
                System.out.println("                             X                              O                              X");
                System.out.println("                            X                               O                               X");
                System.out.println("                           X                                                                 X");
                System.out.println("                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                            X                                                               X");
                System.out.println("                           X                                O                                X");
                System.out.println("                          X                                 O                                 X");
                System.out.println("                         X                                  O                                  X");
                System.out.println("                        X                                   O                                   X");
                System.out.println("                       X                                    O                                    X");
                System.out.println("                      X                                     O                                     X");
                System.out.println("                     X                                      O                                      X");
                System.out.println("                    X                                       O                                       X");
                System.out.println("                   X                                                                                 X");
                System.out.println("                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                    X                                                                               X");
                System.out.println("                   X                                        O                                        X");
                System.out.println("                  X                                         O                                         X");
                System.out.println("                 X                                          O                                          X");
                System.out.println("                X                                           O                                           X");
                System.out.println("               X                                            O                                            X");
                System.out.println("              X                                             O                                             X");
                System.out.println("             X                                              O                                              X");
                System.out.println("            X                                               O                                               X");
                System.out.println("           X                                                O                                                X");
                System.out.println("          X                                                                                                   X");
                System.out.println("           XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("           X                                                                                                 X");
                System.out.println("          X                                                 O                                                 X");
                System.out.println("         X                                                  O                                                  X");
                System.out.println("        X                                                   O                                                   X");
                System.out.println("       X                                                    O                                                    X");
                System.out.println("      X                                                     O                                                     X");
                System.out.println("     X                                                      O                                                      X");
                System.out.println("    X                                                       O                                                       X");
                System.out.println("   X                                                        O                                                        X");
                System.out.println("  X                                                         O                                                         X");
                System.out.println(" X                                                          O                                                          X");
                System.out.println("X                                                                                                                       X");
                System.out.println(" XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
                System.out.println("                                                        OOOO OOOO");
                System.out.print("                                                        OOOO OOOO");
            }
            if(i < 3){
                System.out.println("");
            }
        }
    }
}
